
import javax.swing.JOptionPane;
//import java.util.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mesba Sarif Khan
 */
public class puz extends javax.swing.JFrame {
    private Timer t;
    private int count= 0;
    
    

    /**
     * Creates new form puz
     */
    public puz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Puzzle Game");
        setBackground(new java.awt.Color(0, 153, 153));
        setMinimumSize(new java.awt.Dimension(400, 450));
        setPreferredSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 450));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(null);

        jButton1.setBackground(new java.awt.Color(183, 84, 187));
        jButton1.setText("1");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(10, 5, 39, 23);

        jButton2.setBackground(new java.awt.Color(58, 117, 237));
        jButton2.setText("2");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(55, 5, 39, 23);

        jButton3.setBackground(new java.awt.Color(124, 77, 77));
        jButton3.setText("3");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(104, 5, 39, 23);

        jButton13.setBackground(new java.awt.Color(0, 153, 153));
        jButton13.setText("4");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);
        jButton13.setBounds(10, 34, 39, 23);

        jButton14.setBackground(new java.awt.Color(114, 180, 97));
        jButton14.setText("5");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14);
        jButton14.setBounds(55, 34, 39, 23);

        jButton15.setBackground(new java.awt.Color(102, 123, 124));
        jButton15.setText("6");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15);
        jButton15.setBounds(104, 34, 39, 23);

        jButton16.setBackground(new java.awt.Color(255, 153, 153));
        jButton16.setText("7");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16);
        jButton16.setBounds(10, 68, 39, 23);

        jButton17.setBackground(new java.awt.Color(71, 209, 186));
        jButton17.setText("8");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17);
        jButton17.setBounds(55, 68, 39, 23);

        jButton18.setBackground(new java.awt.Color(86, 90, 185));
        jButton18.setText("9");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18);
        jButton18.setBounds(104, 68, 39, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 210, 150, 100);

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0)));

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jTextField4)
                    .addComponent(jTextField7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 10, 160, 110);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setLayout(null);

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setText("1");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(10, 11, 39, 23);

        jButton5.setBackground(new java.awt.Color(102, 255, 204));
        jButton5.setText("2");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(59, 11, 39, 23);

        jButton6.setBackground(new java.awt.Color(104, 99, 154));
        jButton6.setText("3");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(108, 11, 39, 23);

        jButton7.setBackground(new java.awt.Color(83, 149, 47));
        jButton7.setText("4");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(10, 40, 39, 23);

        jButton8.setBackground(new java.awt.Color(82, 97, 176));
        jButton8.setText("5");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(60, 40, 39, 23);

        jButton9.setBackground(new java.awt.Color(79, 69, 94));
        jButton9.setText("6");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(110, 40, 39, 23);

        jButton10.setBackground(new java.awt.Color(159, 190, 101));
        jButton10.setText("7");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);
        jButton10.setBounds(10, 69, 39, 23);

        jButton11.setBackground(new java.awt.Color(42, 97, 99));
        jButton11.setText("8");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);
        jButton11.setBounds(59, 69, 39, 23);

        jButton12.setBackground(new java.awt.Color(121, 55, 68));
        jButton12.setText("9");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(110, 70, 39, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(220, 210, 160, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Position");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 190, 50, 15);

        jButton19.setBackground(new java.awt.Color(0, 153, 51));
        jButton19.setText("Undo");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(280, 320, 70, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Number");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 190, 50, 15);

        jToggleButton1.setBackground(new java.awt.Color(255, 102, 102));
        jToggleButton1.setText("Restart");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(50, 320, 69, 23);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField10.setBackground(new java.awt.Color(204, 204, 255));
        jTextField10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 0, 0));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton20.setBackground(new java.awt.Color(14, 106, 0));
        jButton20.setText("Start");
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(209, 26, 26));
        jButton21.setText("Stop");
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(140, 130, 130, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
push(2);
p2=1;
   /* g1=0;
    g2=1;
    g3=0;
    g4=0;
    g5=0;
    g6=0;
    g7=0;
    g8=0;
    g9=0;*/
    
     if(jTextField2.getText().isEmpty())
    {
      /*n1=1;
      n2=1;
      n3=1;
      n4=1;
      n5=1;
      n6=1;
      n7=1;
      n8=1;
      n9=1;*/
     jTextField2.setText(s);
      s="";
      jButton2.setEnabled(false);
        if(n1==1||n2==1||n3==1||n4==1||n5==1||n6==1||n7==1||n8==1||n9==1)
  {
      p2=0;
  }
      //p2=0;
  }
   
   
      check();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
push(12);
    s="3";
    n3=1;
    
    
    /*t1=0;
    t2=0;
    t3=1;
    t4=0;
    t5=0;
    t6=0;
    t7=0;
    t8=0;
    t9=0;*/
     if(n3==1)
    {
        jButton6.setEnabled(false);
    }
    if(p1==1&&n3==1)
    {
    
    
    jTextField1.setText(s);
    
   n3=0;
   p1=0;
   s="";
    }
     if(p2==1&&n3==1)
    {
    
    
    jTextField2.setText(s);
    
   n3=0;
   p2=0;
   s="";
    }
      if(p3==1&&n3==1)
    {
    
    
    jTextField3.setText(s);
    
   n3=0;
   p3=0;
   s="";
    }
      if(p4==1&&n3==1)
    {
    
    
    jTextField4.setText(s);
    
   n3=0;
   p4=0;
   s="";
    }
      if(p5==1&&n3==1)
    {
    
    
    jTextField5.setText(s);
    
   n3=0;
   p5=0;
   s="";
    }
      if(p6==1&&n3==1)
    {
    
    
    jTextField6.setText(s);
    
   n3=0;
   p6=0;
   s="";
    }
      if(p7==1&&n3==1)
    {
    
    
    jTextField7.setText(s);
    
   n3=0;
   p7=0;
   s="";
    }
    if(p8==1&&n3==1)
    {
    
    
    jTextField8.setText(s);
    
   n3=0;
   p8=0;
   s="";
    }
    if(p9==1&&n3==1)
    {
    
    
    jTextField9.setText(s);
    
   n3=0;
   p9=0;
   s="";
    }
    check();

                           // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
push(10);
    s="1";
    n1=1;
    
   /* t1=1;
    t2=0;
    t3=0;
    t4=0;
    t5=0;
    t6=0;
    t7=0;
    t8=0;
    t9=0;*/
    
    
    if(n1==1)
    {
        jButton4.setEnabled(false);
    }
    if(p1==1&&n1==1)
    {
    
    
    jTextField1.setText(s);
    
   n1=0;
   p1=0;
   s="";
                         
    }//GEN-LAST:event_jButton4ActionPerformed
   if(p2==1&&n1==1)
    {
    
    
       jTextField2.setText(s);
    
     n1=0;
    p2=0;
    s="";
                         
    }
   if(p3==1&&n1==1)
   {
       jTextField3.setText(s);
       p3=0;
       n1=0;
       s="";
   }
   if(p4==1&&n1==1)
   {
       jTextField4.setText(s);
       p4=0;
       n1=0;
       s="";
   }
   if(p5==1&&n1==1)
   {
       jTextField5.setText(s);
       p5=0;
       n1=0;
       s="";
   }
   if(p6==1&&n1==1)
   {
       jTextField6.setText(s);
       p6=0;
       n1=0;
       s="";
   }
   if(p7==1&&n1==1)
   {
       jTextField7.setText(s);
       p7=0;
       n1=0;
       s="";
   }
    if(p8==1&&n1==1)
   {
       jTextField8.setText(s);
       p8=0;
       n1=0;
       s="";
   }
    if(p9==1&&n1==1)
   {
       jTextField9.setText(s);
       p9=0;
       n1=0;
       s="";
   }
    
    /*if(!jTextField1.getText().isEmpty())
    {
        jButton1.setEnabled(false);
    }*/
    check();
        
    }
    int pos1=0,pos2=0,pos3=0,but2=0,but1=0,but3=0;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
push(11);
        s="2";
   n2=1;
  
    /*t1=0;
    t2=1;
    t3=0;
    t4=0;
    t5=0;
    t6=0;
    t7=0;
    t8=0;
    t9=0;*/
   
    if(n2==1)
    {
        jButton5.setEnabled(false);
    }
     if(p2==1&&n2==1)
    {
    
       jTextField2.setText(s);
       p2=0;
       n2=0;
       s="";
    }
    
    
    if(p1==1&&n2==1)
    {
         jTextField1.setText(s);
         p1=0;
         n2=0;
         s="";
    }
    if(p3==1&&n2==1)
    {
        jTextField3.setText(s);
        p3=0;
        n2=0;
        s="";
    }
    if(p4==1&&n2==1)
    {
    
       jTextField4.setText(s);
       p4=0;
       n2=0;
       s="";
    }
    if(p5==1&&n2==1)
    {
    
       jTextField5.setText(s);
       p5=0;
       n2=0;
       s="";
    }
    if(p6==1&&n2==1)
    {
    
       jTextField6.setText(s);
       p6=0;
       n2=0;
       s="";
    }
    if(p7==1&&n2==1)
    {
    
       jTextField7.setText(s);
       p7=0;
       n2=0;
       s="";
    }
    if(p8==1&&n2==1)
    {
    
       jTextField8.setText(s);
       p8=0;
       n2=0;
       s="";
    }
    if(p9==1&&n2==1)
    {
    
       jTextField9.setText(s);
       p9=0;
       n2=0;
       s="";
    } 
    check();
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   push(1);
   p1=1;
    
   /* g1=1;
    g2=0;
    g3=0;
    g4=0;
    g5=0;
    g6=0;
    g7=0;
    g8=0;
    g9=0;*/
    
    
    
        if(jTextField1.getText().isEmpty())
    {
     /* n1=1;
      n2=1;
      n3=1;
      n4=1;
      n5=1;
      n6=1;
      n7=1;
      n8=1;
      n9=1;*/
     jTextField1.setText(s);
      s=""; 
      jButton1.setEnabled(false);
      if(n1==1||n2==1||n3==1||n4==1||n5==1||n6==1||n7==1||n8==1||n9==1)
  {
      p1=0;
  }
    }//GEN-LAST:event_jButton1ActionPerformed
         
  
  
   check();
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
push(3);
     p3=1; 
        /*    
     g1=0;
    g2=0;
    g3=1;
    g4=0;
    g5=0;
    g6=0;
    g7=0;
    g8=0;
    g9=0;*/
    
        if(jTextField3.getText().isEmpty())
    {
     /* n1=1;
      n2=1;
      n3=1;
      n4=1;
      n5=1;
      n6=1;
      n7=1;
      n8=1;
      n9=1;*/
     jTextField3.setText(s);
      s="";
      jButton3.setEnabled(false);
       if(n1==1||n2==1||n3==1||n4==1||n5==1||n6==1||n7==1||n8==1||n9==1)
  {
      p3=0;
  }
     
    }
       
     
     check();  
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        push(13);
        
        s="4";
    n4=1;
    
   /*  t1=0;
    t2=0;
    t3=0;
    t4=1;
    t5=0;
    t6=0;
    t7=0;
    t8=0;
    t9=0;*/
    
    
    if(n4==1)
    {
        jButton7.setEnabled(false);
    }
    if(p1==1&&n4==1)
    {
    
    
    jTextField1.setText(s);
    
   n4=0;
   p1=0;
   s="";
                         
    }                                        
   if(p2==1&&n4==1)
    {
    
    
       jTextField2.setText(s);
    
     n4=0;
    p2=0;
    s="";
                         
    }
   if(p3==1&&n4==1)
   {
       jTextField3.setText(s);
       p3=0;
       n4=0;
       s="";
   }
   if(p4==1&&n4==1)
   {
       jTextField4.setText(s);
       p4=0;
       n4=0;
       s="";
   }   
   if(p5==1&&n4==1)
   {
       jTextField5.setText(s);
       p5=0;
       n4=0;
       s="";
   }   
   if(p6==1&&n4==1)
   {
       jTextField6.setText(s);
       p6=0;
       n4=0;
       s="";
   }   
   if(p7==1&&n4==1)
   {
       jTextField7.setText(s);
       p7=0;
       n4=0;
       s="";
   }  
   if(p8==1&&n4==1)
   {
       jTextField8.setText(s);
       p8=0;
       n4=0;
       s="";
   }   
   if(p9==1&&n4==1)
   {
       jTextField9.setText(s);
       p9=0;
       n4=0;
       s="";
   } 
   check();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
push(14);
        s="5";
    n5=1;
    
   /* t1=0;
    t2=0;
    t3=0;
    t4=0;
    t5=1;
    t6=0;
    t7=0;
    t8=0;
    t9=0;*/
    if(n5==1)
    {
        jButton8.setEnabled(false);
    }
    if(p1==1&&n5==1)
    {
    
    
    jTextField1.setText(s);
    
   n5=0;
   p1=0;
   s="";
                         
    }
    if(p2==1&&n5==1)
    {
    
    
    jTextField2.setText(s);
    
   n5=0;
   p2=0;
   s="";
                         
    }
   if(p3==1&&n5==1)
    {
    
    
    jTextField3.setText(s);
    
   n5=0;
   p3=0;
   s="";
                         
    }
   if(p4==1&&n5==1)
    {
    
    
    jTextField4.setText(s);
    
   n5=0;
   p4=0;
   s="";
                         
    }
   if(p5==1&&n5==1)
    {
    
    
    jTextField5.setText(s);
    
   n5=0;
   p5=0;
   s="";
                         
    } 
   if(p6==1&&n5==1)
    {
    
    
    jTextField6.setText(s);
    
   n5=0;
   p6=0;
   s="";
                         
    }
   if(p7==1&&n5==1)
    {
    
    
    jTextField7.setText(s);
    
   n5=0;
   p7=0;
   s="";
                         
    }
   if(p8==1&&n5==1)
    {
    
    
    jTextField8.setText(s);
    
   n5=0;
   p8=0;
   s="";
                         
    }
   if(p9==1&&n5==1)
    {
    
    
    jTextField9.setText(s);
    
   n5=0;
   p9=0;
   s="";
                         
    } 
   
   check();
   
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    push(15);
        s="6";
    n6=1;
    
    /* t1=0;
    t2=0;
    t3=0;
    t4=0;
    t5=0;
    t6=1;
    t7=0;
    t8=0;
    t9=0;*/
    if(n6==1)
    {
        jButton9.setEnabled(false);
    }
    if(p1==1&&n6==1)
    {
    
    
    jTextField1.setText(s);
    
   n6=0;
   p1=0;
   s="";
                         
    }
     if(p2==1&&n6==1)
    {
    
    
    jTextField2.setText(s);
    
   n6=0;
   p2=0;
   s="";
                         
    }
    if(p3==1&&n6==1)
    {
    
    
    jTextField3.setText(s);
    
   n6=0;
   p3=0;
   s="";
                         
    }
     if(p4==1&&n6==1)
    {
    
    
    jTextField4.setText(s);
    
   n6=0;
   p4=0;
   s="";
                         
    }
      if(p5==1&&n6==1)
    {
    
    
    jTextField5.setText(s);
    
   n6=0;
   p5=0;
   s="";
                         
    }
       if(p6==1&&n6==1)
    {
    
    
    jTextField6.setText(s);
    
   n6=0;
   p6=0;
   s="";
                         
    }
    if(p7==1&&n6==1)
    {
    
    
    jTextField7.setText(s);
    
   n6=0;
   p7=0;
   s="";
                         
    }
     if(p8==1&&n6==1)
    {
    
    
    jTextField8.setText(s);
    
   n6=0;
   p8=0;
   s="";
                         
    }
      if(p9==1&&n6==1)
    {
    
    
    jTextField9.setText(s);
    
   n6=0;
   p9=0;
   s="";
                         
    } 
      check();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    push(16);
        s="7";
    n7=1;
    
    /* t1=0;
    t2=0;
    t3=0;
    t4=0;
    t5=0;
    t6=0;
    t7=1;
    t8=0;
    t9=0;*/
    
    
    if(n7==1)
    {
        jButton10.setEnabled(false);
    }
    if(p1==1&&n7==1)
    {
    
    
    jTextField1.setText(s);
    
   n7=0;
   p1=0;
   s="";
                         
    }
   if(p2==1&&n7==1)
    {
    
    
    jTextField2.setText(s);
    
   n7=0;
   p2=0;
   s="";
                         
    }
   if(p3==1&&n7==1)
    {
    
    
    jTextField3.setText(s);
    
   n7=0;
   p3=0;
   s="";
                         
    }
   if(p4==1&&n7==1)
    {
    
    
    jTextField4.setText(s);
    
   n7=0;
   p4=0;
   s="";
                         
    }
   if(p5==1&&n7==1)
    {
    
    
    jTextField5.setText(s);
    
   n7=0;
   p5=0;
   s="";
                         
    }
   if(p6==1&&n7==1)
    {
    
    
    jTextField6.setText(s);
    
   n7=0;
   p6=0;
   s="";
                         
    }
   if(p7==1&&n7==1)
    {
    
    
    jTextField7.setText(s);
    
   n7=0;
   p7=0;
   s="";
                         
    }
   if(p8==1&&n7==1)
    {
    
    
    jTextField8.setText(s);
    
   n7=0;
   p8=0;
   s="";
                         
    }
   if(p9==1&&n7==1)
    {
    
    jTextField9.setText(s);
    
   n7=0;
   p9=0;
   s="";
                         
    }
   check();
    
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    
        push(17);
        s="8";
    n8=1;
    
    /*t1=0;
    t2=0;
    t3=0;
    t4=0;
    t5=0;
    t6=0;
    t7=0;
    t8=1;
    t9=0;*/
    if(n8==1)
    {
        jButton11.setEnabled(false);
    }
    if(p1==1&&n8==1)
    {
    
    
    jTextField1.setText(s);
    
   n8=0;
   p1=0;
   s="";
                         
    } 
    if(p2==1&&n8==1)
    {
    
    
    jTextField2.setText(s);
    
   n8=0;
   p2=0;
   s="";
                         
    }
    if(p3==1&&n8==1)
    {
    
    
    jTextField3.setText(s);
    
   n8=0;
   p3=0;
   s="";
                         
    }
    if(p4==1&&n8==1)
    {
    
    
    jTextField4.setText(s);
    
   n8=0;
   p4=0;
   s="";
                         
    }
    if(p5==1&&n8==1)
    {
    
    
    jTextField5.setText(s);
    
   n8=0;
   p5=0;
   s="";
                         
    }
    if(p6==1&&n8==1)
    {
    
    
    jTextField6.setText(s);
    
   n8=0;
   p6=0;
   s="";
                         
    }
    if(p7==1&&n8==1)
    {
    
    
    jTextField7.setText(s);
    
   n8=0;
   p7=0;
   s="";
                         
    }
    if(p8==1&&n8==1)
    {
    
    
    jTextField8.setText(s);
    
   n8=0;
   p8=0;
   s="";
                         
    }
    if(p9==1&&n8==1)
    {
    
    
    jTextField9.setText(s);
    
   n8=0;
   p9=0;
   s="";
                         
    }
    check();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    push(18);
        s="9";
    n9=1;
    
    /* t1=0;
    t2=0;
    t3=0;
    t4=0;
    t5=0;
    t6=0;
    t7=0;
    t8=0;
    t9=1;*/
   if(n9==1)
    {
        jButton12.setEnabled(false);
    }
    if(p1==1&&n9==1)
    {
    
    
    jTextField1.setText(s);
    
   n9=0;
   p1=0;
   s="";
                         
    }
    if(p2==1&&n9==1)
    {
    
    
    jTextField2.setText(s);
    
   n9=0;
   p2=0;
   s="";
                         
    }
    if(p3==1&&n9==1)
    {
    
    
    jTextField3.setText(s);
    
   n9=0;
   p3=0;
   s="";
                         
    }
    if(p4==1&&n9==1)
    {
    
    
    jTextField4.setText(s);
    
   n9=0;
   p4=0;
   s="";
                         
    }
    if(p5==1&&n9==1)
    {
    
    
    jTextField5.setText(s);
    
   n9=0;
   p5=0;
   s="";
                         
    }
    if(p6==1&&n9==1)
    {
    
    
    jTextField6.setText(s);
    
   n9=0;
   p6=0;
   s="";
                         
    }
    if(p7==1&&n9==1)
    {
    
    
    jTextField7.setText(s);
    
   n9=0;
   p7=0;
   s="";
                         
    }
    if(p8==1&&n9==1)
    {
    
    
    jTextField8.setText(s);
    
   n9=0;
   p8=0;
   s="";
                         
    }
    if(p9==1&&n9==1)
    {
    
    
    jTextField9.setText(s);
    
   n9=0;
   p9=0;
   s="";
                         
    }
    check();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

    push(4);    
        p4=1;
    
    /*g1=0;
    g2=0;
    g3=0;
    g4=1;
    g5=0;
    g6=0;
    g7=0;
    g8=0;
    g9=0;*/
    
        if(jTextField4.getText().isEmpty())
    {
     /* n1=1;
      n2=1;
      n3=1;
      n4=1;
      n5=1;
      n6=1;
      n7=1;
      n8=1;
      n9=1;*/
      jTextField4.setText(s);
      s="";
       jButton13.setEnabled(false);
       if(n1==1||n2==1||n3==1||n4==1||n5==1||n6==1||n7==1||n8==1||n9==1)
  {
      p4=0;
  } 
    }
       // TODO add your handling code here:
     
      check();
     
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
    push(5); 
        
        p5=1;
  /* g1=0;
    g2=0;
    g3=0;
    g4=0;
    g5=1;
    g6=0;
    g7=0;
    g8=0;
    g9=0;*/
    
        if(jTextField5.getText().isEmpty())
    {
     /* n1=1;
      n2=1;
      n3=1;
      n4=1;
      n5=1;
      n6=1;
      n7=1;
      n8=1;
      n9=1;*/
      jTextField5.setText(s);
      s="";
       jButton14.setEnabled(false);
        if(n1==1||n2==1||n3==1||n4==1||n5==1||n6==1||n7==1||n8==1||n9==1)
  {
      p5=0;
  }
    }
       // TODO add your handling code here:
     
      check();
     
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
push(6);
        p6=1;
     
     
    /*g1=0;
    g2=0;
    g3=0;
    g4=0;
    g5=0;
    g6=1;
    g7=0;
    g8=0;
    g9=0;*/
 
        if(jTextField6.getText().isEmpty())
    {
      /*n1=1;
      n2=1;
      n3=1;
      n4=1;
      n5=1;
      n6=1;
      n7=1;
      n8=1;
      n9=1;*/
      jTextField6.setText(s);
      s="";
       jButton15.setEnabled(false);
         if(n1==1||n2==1||n3==1||n4==1||n5==1||n6==1||n7==1||n8==1||n9==1)
  {
      p6=0;
  } 
    }
      // TODO add your handling code here:
      check();
     
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
push(7); 
    p7=1;
    
    /*g1=0;
    g2=0;
    g3=0;
    g4=0;
    g5=0;
    g6=0;
    g7=1;
    g8=0;
    g9=0;*/
   
        if(jTextField7.getText().isEmpty())
    {
      /*n1=1;
      n2=1;
      n3=1;
      n4=1;
      n5=1;
      n6=1;
      n7=1;
      n8=1;
      n9=1;*/
      jTextField7.setText(s);
      s="";
       jButton16.setEnabled(false);
          if(n1==1||n2==1||n3==1||n4==1||n5==1||n6==1||n7==1||n8==1||n9==1)
  {
      p7=0;
  }
    }
   // TODO add your handling code here:
     
     check(); 
     
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
push(8);
        p8=1;
     
    /*g1=0;
    g2=0;
    g3=0;
    g4=0;
    g5=0;
    g6=0;
    g7=0;
    g8=1;
    g9=0;*/
    
        if(jTextField8.getText().isEmpty())
    {
      /*n1=1;
      n2=1;
      n3=1;
      n4=1;
      n5=1;
      n6=1;
      n7=1;
      n8=1;
      n9=1;*/
      jTextField8.setText(s);
      s="";
      jButton17.setEnabled(false);
          if(n1==1||n2==1||n3==1||n4==1||n5==1||n6==1||n7==1||n8==1||n9==1)
  {
      p8=0;
  } 
    }
     // TODO add your handling code here:
       check();
      
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
    push(9);
        p9=1;
     
     
    /* g1=0;
    g2=0;
    g3=0;
    g4=0;
    g5=0;
    g6=0;
    g7=0;
    g8=0;
    g9=1;*/
   
        if(jTextField9.getText().isEmpty())
    {
     /* n1=1;
      n2=1;
      n3=1;
      n4=1;
      n5=1;
      n6=1;
      n7=1;
      n8=1;
      n9=1;*/
      jTextField9.setText(s);
      s="";
      jButton18.setEnabled(false);
      
    }
      // TODO add your handling code here:
      check();
     
     
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
   
     pop();
     if(p==1)
     {
         jTextField1.setText("");
         jButton1.setEnabled(true);
         
     }
     else  if(p==2)
        {
         jTextField2.setText("");
          jButton2.setEnabled(true);
     }
     else  if(p==3)
        {
         jTextField3.setText("");
          jButton3.setEnabled(true);
     }
     else  if(p==4)
        {
         jTextField4.setText("");
          jButton13.setEnabled(true);
     }
     else  if(p==5)
        {
         jTextField5.setText("");
          jButton14.setEnabled(true);
     }
     else  if(p==6)
        {
         jTextField6.setText("");
          jButton15.setEnabled(true);
     }
     else  if(p==7)
        {
         jTextField7.setText("");
          jButton16.setEnabled(true);
     }
     else  if(p==8)
        {
         jTextField8.setText("");
          jButton17.setEnabled(true);
     }
     else  if(p==9)
        {
         jTextField9.setText("");
          jButton18.setEnabled(true);
     }
     else  if(p==10)
        {
          jButton4.setEnabled(true);
        }
     else  if(p==11)
        {
          jButton5.setEnabled(true);
        }
     else  if(p==12)
        {
          jButton6.setEnabled(true);
        }
     else  if(p==13)
        {
          jButton7.setEnabled(true);
        }
     else  if(p==14)
        {
          jButton8.setEnabled(true);
        }
     else  if(p==15)
        {
          jButton9.setEnabled(true);
        }
     else  if(p==16)
        {
          jButton10.setEnabled(true);
        }
     else  if(p==17)
        {
          jButton11.setEnabled(true);
        }
     else  if(p==18)
        {
          jButton12.setEnabled(true);
        }   

// TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(true);
        jButton11.setEnabled(true);
        jButton12.setEnabled(true);
        jButton13.setEnabled(true);
        jButton14.setEnabled(true);
        jButton15.setEnabled(true);
        jButton16.setEnabled(true);
        jButton17.setEnabled(true);
        jButton18.setEnabled(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
  t=new Timer (1000, new ActionListener(){
   @Override
   public void actionPerformed(ActionEvent e) {
      count++;
     jTextField10.setText(count + " " + "s");
   }
   
   });
  t.start(); 
  check();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
     t.stop();
     check();// TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed
   
      
  
    String s=new String();
    void check()
    {
        int j=0;
        if(!jTextField1.getText().isEmpty())
        {
            f1=Integer.parseInt(jTextField1.getText());
            j++;
        }
        if(!jTextField2.getText().isEmpty())
        {
            f2=Integer.parseInt(jTextField2.getText());
            j++;
        }
        if(!jTextField3.getText().isEmpty())
        {
            f3=Integer.parseInt(jTextField3.getText());
            j++;
        }
        if(!jTextField4.getText().isEmpty())
        {
            f4=Integer.parseInt(jTextField4.getText());
            j++;
        }
        if(!jTextField5.getText().isEmpty())
        {
            f5=Integer.parseInt(jTextField5.getText());
            j++;
        }
        if(!jTextField6.getText().isEmpty())
        {
            f6=Integer.parseInt(jTextField6.getText());
            j++;
        }
        if(!jTextField7.getText().isEmpty())
        {
            f7=Integer.parseInt(jTextField7.getText());
            j++;
        }
        if(!jTextField8.getText().isEmpty())
        {
            f8=Integer.parseInt(jTextField8.getText());
            j++;
        }
        if(!jTextField9.getText().isEmpty())
        {
            f9=Integer.parseInt(jTextField9.getText());
            j++;
        }
        
        if(f1+f2+f3==15 && f4+f5+f6==15 && f7+f8+f9==15 && f1+f4+f7==15 && f2+f5+f8==15 && f3+f6+f9==15 && f1+f5+f9==15 && f3+f5+f7==15)
        {
            t.stop();
            
            JOptionPane.showMessageDialog(this,"You win");
        }
       else if(j==9)
        {
            t.stop();
            JOptionPane.showMessageDialog(this,"You lose");
        }
        
        
        
    }
   void display()
   {
        System.out.println(f1);
   }
   int counter=10;
   public void start()
   {
       jTextField10.setText(Integer.toString(counter));
       counter--;
       
   }
   
 
    
    int f1=0,f2=0,f3=0,f4=0,f5=0,f6=0,f7=0,f8=0,f9=0;
    int n1,n2,n3,n4,n5,n6,n7,n8,n9;
    int p1,p2,p3,p4,p5,p6,p7,p8,p9;
    int g1,g2,g3,g4,g5,g6,g7,g8,g9;
    int t1,t2,t3,t4,t5,t6,t7,t8,t9;
    int a[]=new int[100];
    int top=-1;
    int p;
    public void push(int j)
    {
        top++;
        a[top]=j;
        
        
    }
    public int pop()
    {
       p= a[top];
       top--;
       return p;
       
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
puz p=new puz();

//p.display();
p.start();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
